{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-bitbucket
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{.Values.ingress.fqdn}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-bitbucket
            port:
              number: 7990
{{- end }}
