---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.postgres.username_base64 }}
  password: {{ .Values.postgres.password_base64 }}
  postgres_db: {{ .Values.postgres.database_name }}