---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsyslog-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: rsyslog
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: rsyslog
  template:
    metadata:
      labels:
        app: rsyslog
    spec:
      containers:
      - name: rsyslog
        image: {{.Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 514
        resources:
          requests:
            cpu: 250m
            memory: 524Mi
{{- if .Values.persistentvolume.enabled }}
        volumeMounts:
        - name: rsyslog-data
          mountPath: /var/log/remote
      volumes:
      - name: rsyslog-data
        persistentVolumeClaim:
          claimName: rsyslog-pvc
{{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
