---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-user-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
- kind: User
  name: {{ .Values.namespace }}-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-user-role
  apiGroup: rbac.authorization.k8s.io