---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-user-role
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
