defaultNamespace: cattle-monitoring-system
helm:
  repo: https://charts.rancher.io
  chart: rancher-monitoring
  version: 104.1.0+up57.0.3
  releaseName: rancher-monitoring
  valuesFile:
  - values.yaml
  values:
    proxy:
      enabled: true
    rke2ControllerManager:
      enabled: true
    rke2Scheduler:
      enabled: true
    rke2Proxy:
      enabled: true
    rke2Etcd:
      enabled: true
    rke2IngressNginx:
      enabled: true
      
