defaultNamespace: cattle-monitoring-system
helm:
  # repo: https://charts.rancher.io
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 62.7.0
  releaseName: rancher-monitoring
  # valuesFiles:
  #   - values.yaml
  # values:
  #   labels:
  #     catalog.cattle.io/cluster-repo-name: rancher-charts
# dependsOn:
#   - name: "k8s-provisioner-prod-monitoring-crd"
#   - name: "k8s-provisioner-prod-longhorn"
