defaultNamespace: cattle-monitoring-system
helm:
  repo: https://charts.rancher.io
  chart: rancher-monitoring
  version: 104.1.0+up57.0.3
  releaseName: rancher-monitoring
  values:
    global:
      cattle:
        clusterId: c-m-nqn6j745
        clusterName: rke2-fleet-monitor
        rkePathPrefix: ""
        rkeWindowsPathPrefix: ""
        systemDefaultRegistry: registry.rancher.com
        systemProjectId: p-cvnt4
        url: https://rancher.somequant.club
      systemDefaultRegistry: registry.rancher.com
    prometheus:
      prometheusSpec:
        retentionSize: 50GiB
    rke2ControllerManager:
      enabled: true
    rke2Etcd:
      enabled: true
    rke2IngressNginx:
      enabled: true
    rke2Proxy:
      enabled: true
    rke2Scheduler:
      enabled: true
      
