# Default values for sysdepot-logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: your-name

persistentvolume:
  enabled: true
  volSize: 10Gi

postgres:
  username_base64: ""
  password_base64: ""
  database_name: "postgres"

# postgres-service.{{namespace}}.svc.cluster.local